#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

/// MACROS ///

#define BORDURE_ANGLE_HD char(191)
#define BORDURE_ANGLE_BD char(217)
#define BORDURE_ANGLE_HG char(218)
#define BORDURE_ANGLE_BG char(192)
#define BORDURE_BARRE_HORZ char(196)
#define BORDURE_BARRE_VERT char(179)
#define BORDURE_INTER3_HAUT char(193)
#define BORDURE_INTER3_BAS char(194)
#define BORDURE_INTER3_DROITE char(195)
#define BORDURE_INTER3_GAUCHE char(180)
#define BORDURE_INTER4 char(197)

#define CARAC_CARRE char(254)

/// CONSTANTES ///

#define TAILLE_PLATEAU 8
#define LIGNE_AFFICHAGE 5
#define COLONNE_AFFICHAGE 4

#endif // CONSTANTES_H_INCLUDED
